### PR TITLE
Update os.py

### PR DESCRIPTION
**Pull request by likenamehaojie**
## Type of change

- [x] Bugfix: ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id, AttributeError: 'NoneType' object has no attribute 'id' AttributeError: 'NoneType' object has no attribute 'id'
when update to 2023.03.03

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by likenamehaojie** [comment]
Signed-off-by: likenamehaojie@hotmail.com

**Comment by likenamehaojie** [comment]
1

**Comment by mdegat01** [comment]
This would break the API for everyone on a supported system. Since on supported systems, `disk_used` is not `None` and is a python object.

#4221 is a proper fix for this issue. Closing this.
